<?php 
function all_html_entities_decode($input, $mode) { 
    $html_entities = array( 
        #array('"','&quot;','&#34;'), # Anführungszeichen oben 
        #array('&','&amp;','&#38;'), # Ampersand-Zeichen, kaufmännisches Und' 
        #array('<','&lt;','&#60;'), # öffnende spitze Klammer' 
        #array('>','&gt;','&#62;'), # schließende spitze Klammer' 
        array(' ','&nbsp;','&#160;'), # Erzwungenes Leerzeichen' 
        array('¡','&iexcl;','&#161;'), # umgekehrtes Ausrufezeichen' 
        array('¢','&cent;','&#162;'), # Cent-Zeichen' 
        array('£','&pound;','&#163;'), # Pfund-Zeichen' 
        array('¤','&curren;','&#164;'), # Währungszeichen' 
        array('¥','&yen;','&#165;'), # Yen-Zeichen' 
        array('¦','&brvbar;','&#166;'), # durchbrochener Strich' 
        array('§','&sect;','&#167;'), # Paragraph-Zeichen' 
        array('¨','&uml;','&#168;'), # Pünktchen oben' 
        array('©','&copy;','&#169;'), # Copyright-Zeichen' 
        array('ª','&ordf;','&#170;'), # Ordinal-Zeichen weiblich' 
        array('«','&laquo;','&#171;'), # angewinkelte Anführungszeichen links' 
        array('»','&raquo;','&#187;'), # angewinkelte Anführungszeichen rechts' 
        array('¬','&not;','&#172;'), # Verneinungs-Zeichen' 
        array('­','&shy;','&#173;'), # bedingter Trennstrich' 
        array('®','&reg;','&#174;'), # Registriermarke-Zeichen' 
        array('¯','&macr;','&#175;'), # Überstrich' 
        array('°','&deg;','&#176;'), # Grad-Zeichen' 
        array('±','&plusmn;','&#177;'), # Plusminus-Zeichen' 
        array('²','&sup2;','&#178;'), # Hoch-2-Zeichen' 
        array('³','&sup3;','&#179;'), # Hoch-3-Zeichen' 
        array('´','&acute;','&#180;'), # Akut-Zeichen' 
        array('µ','&micro;','&#181;'), # Mikro-Zeichen' 
        array('¶','&para;','&#182;'), # Absatz-Zeichen' 
        array('·','&middot;','&#183;'), # Mittelpunkt' 
        array('¸','&cedil;','&#184;'), # Häkchen unten' 
        array('¹','&sup1;','&#185;'), # Hoch-1-Zeichen' 
        array('º','&ordm;','&#186;'), # Ordinal-Zeichen männlich' 
        array('¼','&frac14;','&#188;'), # ein Viertel' 
        array('½','&frac12;','&#189;'), # ein Halb' 
        array('¾','&frac34;','&#190;'), # drei Viertel' 
        array('¿','&iquest;','&#191;'), # umgekehrtes Fragezeichen' 
        array('À','&Agrave;','&#192;'), # A mit accent grave (Gravis)' 
        array('Á','&Aacute;','&#193;'), # A mit accent aigu (Akut)' 
        array('Â','&Acirc;','&#194;'), # A mit Zirkumflex' 
        array('Ã','&Atilde;','&#195;'), # A mit Tilde' 
        array('Ä','&Auml;','&#196;'), # A Umlaut' 
        array('Å','&Aring;','&#197;'), # A mit Ring' 
        array('Æ','&AElig;','&#198;'), # A mit legiertem E' 
        array('Ç','&Ccedil;','&#199;'), # C mit Häkchen' 
        array('È','&Egrave;','&#200;'), # E mit accent grave (Gravis)' 
        array('É','&Eacute;','&#201;'), # E mit accent aigu (Akut)' 
        array('Ê','&Ecirc;','&#202;'), # E mit Zirkumflex' 
        array('Ë','&Euml;','&#203;'), # E Umlaut' 
        array('Ì','&Igrave;','&#204;'), # I mit accent grave (Gravis)' 
        array('Í','&Iacute;','&#205;'), # I mit accent aigu (Akut)' 
        array('Î','&Icirc;','&#206;'), # I mit Zirkumflex' 
        array('Ï','&Iuml;','&#207;'), # I Umlaut' 
        array('Ð','&ETH;','&#208;'), # großes Eth (isländisch)' 
        array('Ñ','&Ntilde;','&#209;'), # N mit Tilde' 
        array('Ò','&Ograve;','&#210;'), # O mit accent grave (Gravis)' 
        array('Ó','&Oacute;','&#211;'), # O mit accent aigu (Akut)' 
        array('Ô','&Ocirc;','&#212;'), # O mit Zirkumflex' 
        array('Õ','&Otilde;','&#213;'), # O mit Tilde' 
        array('Ö','&Ouml;','&#214;'), # O Umlaut' 
        array('×','&times;','&#215;'), # Mal-Zeichen' 
        array('Ø','&Oslash;','&#216;'), # O mit Schrägstrich' 
        array('Ù','&Ugrave;','&#217;'), # U mit accent grave (Gravis)' 
        array('Ú','&Uacute;','&#218;'), # U mit accent aigu (Akut)' 
        array('Û','&Ucirc;','&#219;'), # U mit Zirkumflex' 
        array('Ü','&Uuml;','&#220;'), # U Umlaut' 
        array('Ý','&Yacute;','&#221;'), # Y mit accent aigu (Akut)' 
        array('Þ','&THORN;','&#222;'), # großes Thorn (isländisch)' 
        array('ß','&szlig;','&#223;'), # scharfes S' 
        array('à','&agrave;','&#224;'), # a mit accent grave (Gravis)' 
        array('á','&aacute;','&#225;'), # a mit accent aigu (Akut)' 
        array('â','&acirc;','&#226;'), # a mit Zirkumflex' 
        array('ã','&atilde;','&#227;'), # a mit Tilde' 
        array('ä','&auml;','&#228;'), # a Umlaut' 
        array('å','&aring;','&#229;'), # a mit Ring' 
        array('æ','&aelig;','&#230;'), # a mit legiertem e' 
        array('ç','&ccedil;','&#231;'), # c mit Häkchen' 
        array('è','&egrave;','&#232;'), # e mit accent grave (Gravis)' 
        array('é','&eacute;','&#233;'), # e mit accent aigu (Akut)' 
        array('ê','&ecirc;','&#234;'), # e mit Zirkumflex' 
        array('ë','&euml;','&#235;'), # e Umlaut' 
        array('ì','&igrave;','&#236;'), # i mit accent grave (Gravis)' 
        array('í','&iacute;','&#237;'), # i mit accent aigu (Akut)' 
        array('î','&icirc;','&#238;'), # i mit Zirkumflex' 
        array('ï','&iuml;','&#239;'), # i Umlaut' 
        array('ð','&eth;','&#240;'), # kleines Eth (isländisch)' 
        array('ñ','&ntilde;','&#241;'), # n mit Tilde' 
        array('ò','&ograve;','&#242;'), # o mit accent grave (Gravis)' 
        array('ó','&oacute;','&#243;'), # o mit accent aigu (Akut)' 
        array('ô','&ocirc;','&#244;'), # o mit Zirkumflex' 
        array('õ','&otilde;','&#245;'), # o mit Tilde' 
        array('ö','&ouml;','&#246;'), # o Umlaut' 
        array('÷','&divide;','&#247;'), # Divisions-Zeichen' 
        array('ø','&oslash;','&#248;'), # o mit Schrägstrich' 
        array('ù','&ugrave;','&#249;'), # u mit accent grave (Gravis)' 
        array('ú','&uacute;','&#250;'), # u mit accent aigu (Akut)' 
        array('û','&ucirc;','&#251;'), # u mit Zirkumflex' 
        array('ü','&uuml;','&#252;'), # u Umlaut' 
        array('ý','&yacute;','&#253;'), # y mit accent aigu (Akut)' 
        array('þ','&thorn;','&#254;'), # kleines Thorn (isländisch)' 
        array('ÿ','&yuml;','&#255;'), # y Umlaut' 
        array('Α','&Alpha;','&#913;'), # Alpha groß' 
        array('α','&alpha;','&#945;'), # alpha klein' 
        array('Β','&Beta;','&#914;'), # Beta groß' 
        array('β','&beta;','&#946;'), # beta klein' 
        array('Γ','&Gamma;','&#915;'), # Gamma groß' 
        array('γ','&gamma;','&#947;'), # gamma klein' 
        array('Δ','&Delta;','&#916;'), # Delta groß' 
        array('δ','&delta;','&#948;'), # delta klein' 
        array('Ε','&Epsilon;','&#917;'), # Epsilon groß' 
        array('ε','&epsilon;','&#949;'), # epsilon klein' 
        array('Ζ','&Zeta;','&#918;'), # Zeta groß' 
        array('ζ','&zeta;','&#950;'), # zeta klein' 
        array('Η','&Eta;','&#919;'), # Eta groß' 
        array('η','&eta;','&#951;'), # eta klein' 
        array('Θ','&Theta;','&#920;'), # Theta groß' 
        array('θ','&theta;','&#952;'), # theta klein' 
        array('Ι','&Iota;','&#921;'), # Iota groß' 
        array('ι','&iota;','&#953;'), # iota klein' 
        array('Κ','&Kappa;','&#922;'), # Kappa groß' 
        array('κ','&kappa;','&#954;'), # kappa klein' 
        array('Λ','&Lambda;','&#923;'), # Lambda groß' 
        array('λ','&lambda;','&#955;'), # lambda klein' 
        array('Μ','&Mu;','&#924;'), # My groß' 
        array('μ','&mu;','&#956;'), # my klein' 
        array('Ν','&Nu;','&#925;'), # Ny groß' 
        array('ν','&nu;','&#957;'), # ny klein' 
        array('Ξ','&Xi;','&#926;'), # Xi groß' 
        array('ξ','&xi;','&#958;'), # xi klein' 
        array('Ο','&Omicron;','&#927;'), # Omikron groß' 
        array('ο','&omicron;','&#959;'), # omikron klein' 
        array('Π','&Pi;','&#928;'), # Pi groß' 
        array('π','&pi;','&#960;'), # pi klein' 
        array('Ρ','&Rho;','&#929;'), # Rho groß' 
        array('ρ','&rho;','&#961;'), # rho klein' 
        array('Σ','&Sigma;','&#931;'), # Sigma groß' 
        array('ς','&sigmaf;','&#962;'), # Schluss-Sigma' 
        array('σ','&sigma;','&#963;'), # sigma klein' 
        array('Τ','&Tau;','&#932;'), # Tau groß' 
        array('τ','&tau;','&#964;'), # tau klein' 
        array('Υ','&Upsilon;','&#933;'), # Ypsilon groß' 
        array('υ','&upsilon;','&#965;'), # ypsilon klein' 
        array('Φ','&Phi;','&#934;'), # Phi groß' 
        array('φ','&phi;','&#966;'), # phi klein' 
        array('Χ','&Chi;','&#935;'), # Chi groß' 
        array('χ','&chi;','&#967;'), # chi klein' 
        array('Ψ','&Psi;','&#936;'), # Psi groß' 
        array('ψ','&psi;','&#968;'), # psi klein' 
        array('Ω','&Omega;','&#937;'), # Omega groß' 
        array('ω','&omega;','&#969;'), # omega klein' 
        array('ϑ','&thetasym;','&#977;'), # theta Symbol' 
        array('ϒ','&upsih;','&#978;'), # ypsilon mit Haken' 
        array('ϖ','&piv;','&#982;'), # pi Symbol' 
        array('∀','&forall;','&#8704;'), # für alle' 
        array('∂','&part;','&#8706;'), # partiell' 
        array('∃','&exist;','&#8707;'), # existiert' 
        array('∅','&empty;','&#8709;'), # leere Menge' 
        array('∇','&nabla;','&#8711;'), # Nabla' 
        array('∈','&isin;','&#8712;'), # Element von' 
        array('∉','&notin;','&#8713;'), # kein Element von' 
        array('∋','&ni;','&#8715;'), # Element von (gespiegelt)' 
        array('∏','&prod;','&#8719;'), # Produkt' 
        array('∑','&sum;','&#8721;'), # Summe' 
        array('−','&minus;','&#8722;'), # minus' 
        array('∗','&lowast;','&#8727;'), # Asterisk' 
        array('√','&radic;','&#8730;'), # Wurzel' 
        array('∝','&prop;','&#8733;'), # proportional zu' 
        array('∞','&infin;','&#8734;'), # unendlich' 
        array('∠','&ang;','&#8736;'), # Winkel' 
        array('∧','&and;','&#8743;'), # und' 
        array('∨','&or;','&#8744;'), # oder' 
        array('∩','&cap;','&#8745;'), # Schnittmenge' 
        array('∪','&cup;','&#8746;'), # Vereinigungsmenge' 
        array('∫','&int;','&#8747;'), # Integral' 
        array('∴','&there4;','&#8756;'), # deshalb' 
        array('∼','&sim;','&#8764;'), # ähnlich wie' 
        array('≅','&cong;','&#8773;'), # kongruent' 
        array('≈','&asymp;','&#8776;'), # beinahe gleich' 
        array('≠','&ne;','&#8800;'), # ungleich' 
        array('≡','&equiv;','&#8801;'), # identisch mit' 
        array('≤','&le;','&#8804;'), # kleiner gleich' 
        array('≥','&ge;','&#8805;'), # größer gleich' 
        array('⊂','&sub;','&#8834;'), # Untermenge von' 
        array('⊃','&sup;','&#8835;'), # Obermenge von' 
        array('⊄','&nsub;','&#8836;'), # keine Untermenge von' 
        array('⊆','&sube;','&#8838;'), # Untermenge von oder gleich mit' 
        array('⊇','&supe;','&#8839;'), # Obermenge von oder gleich mit' 
        array('⊕','&oplus;','&#8853;'), # Restklassenaddition' 
        array('⊗','&otimes;','&#8855;'), # Kronecker-Produkt' 
        array('⊥','&perp;','&#8869;'), # senkrecht zu' 
        array('⋅','&sdot;','&#8901;'), # Punkt-Operator' 
        array('◊','&loz;','&#9674;'), # Raute' 
        array('⌈','&lceil;','&#8968;'), # links oben' 
        array('⌉','&rceil;','&#8969;'), # rechts oben' 
        array('⌊','&lfloor;','&#8970;'), # links unten' 
        array('⌋','&rfloor;','&#8971;'), # rechts unten' 
        array('⟨','&lang;','&#9001;'), # spitze Klammer links' 
        array('⟩','&rang;','&#9002;'), # spitze Klammer rechts' 
        array('←','&larr;','&#8592;'), # Pfeil links' 
        array('↑','&uarr;','&#8593;'), # Pfeil oben' 
        array('→','&rarr;','&#8594;'), # Pfeil rechts' 
        array('↓','&darr;','&#8595;'), # Pfeil unten' 
        array('↔','&harr;','&#8596;'), # Pfeil links/rechts' 
        array('↵','&crarr;','&#8629;'), # Pfeil unten-Knick-links' 
        array('⇐','&lArr;','&#8656;'), # Doppelpfeil links' 
        array('⇑','&uArr;','&#8657;'), # Doppelpfeil oben' 
        array('⇒','&rArr;','&#8658;'), # Doppelpfeil rechts' 
        array('⇓','&dArr;','&#8659;'), # Doppelpfeil unten' 
        array('⇔','&hArr;','&#8660;'), # Doppelpfeil links/rechts' 
        array('•','&bull;','&#8226;'), # Bullet-Zeichen' 
        array('′','&prime;','&#8242;'), # Minutenzeichen' 
        array('″','&Prime;','&#8243;'), # Sekundenzeichen' 
        array('‾','&oline;','&#8254;'), # Überstrich' 
        array('⁄','&frasl;','&#8260;'), # Bruchstrich' 
        array('℘','&weierp;','&#8472;'), # Weierstraß p' 
        array('ℑ','&image;','&#8465;'), # Zeichen für "imaginär"' 
        array('ℜ','&real;','&#8476;'), # Zeichen für "real"' 
        array('™','&trade;','&#8482;'), # Trademark-Zeichen' 
        array('€','&euro;','&#8364;'), # Euro-Zeichen' 
        array('ℵ','&alefsym;','&#8501;'), # Alef-Symbol' 
        array('♠','&spades;','&#9824;'), # Pik-Zeichen' 
        array('♣','&clubs;','&#9827;'), # Kreuz-Zeichen' 
        array('♥','&hearts;','&#9829;'), # Herz-Zeichen' 
        array('♦','&diams;','&#9830;'), # Karo-Zeichen' 
        array('Œ','&OElig;','&#338;'), # OE-Ligatur' 
        array('œ','&oelig;','&#339;'), # oe-Ligatur' 
        array('Š','&Scaron;','&#352;'), # S mit Hatschek (Caron)' 
        array('š','&scaron;','&#353;'), # s mit Hatschek (Caron)' 
        array('Ÿ','&Yuml;','&#376;'), # Y Umlaut' 
        array('ƒ','&fnof;','&#402;'), # Funktion' 
        array(' ','&ensp;','&#8194;'), # Leerzeichen Breite n' 
        array(' ','&emsp;','&#8195;'), # Leerzeichen Breite m' 
        array(' ','&thinsp;','&#8201;'), # Schmales Leerzeichen' 
        array('‌','&zwnj;','&#8204;'), # null breiter Nichtverbinder' 
        array('‍','&zwj;','&#8205;'), # null breiter Verbinder' 
        array('‎','&lrm;','&#8206;'), # links-nach-rechts-Zeichen' 
        array('‏','&rlm;','&#8207;'), # rechts-nach-links-Zeichen' 
        array('–','&ndash;','&#8211;'), # Gedankenstrich Breite n' 
        array('—','&mdash;','&#8212;'), # Gedankenstrich Breite m' 
        array('‘','&lsquo;','&#8216;'), # einfaches Anführungszeichen links' 
        array('’','&rsquo;','&#8217;'), # einfaches Anführungszeichen rechts' 
        array('‚','&sbquo;','&#8218;'), # einfaches low-9-Zeichen' 
        array('“','&ldquo;','&#8220;'), # doppeltes Anführungszeichen links' 
        array('”','&rdquo;','&#8221;'), # doppeltes Anführungszeichen rechts' 
        array('„','&bdquo;','&#8222;'), # doppeltes low-9-Zeichen rechts' 
        array('†','&dagger;','&#8224;'), # Kreuz' 
        array('‡','&Dagger;','&#8225;'), # Doppelkreuz' 
        array('…','&hellip;','&#8230;'), # Horizontale Ellipse (Auslassungszeichen)' 
        array('‰','&permil;','&#8240;'), # Promille' 
        array('‹','&lsaquo;','&#8249;'), # angewinkeltes einzelnes Anf.zeichen links' 
        array('›','&rsaquo;','&#8250;'), # angewinkeltes einzelnes Anf.zeichen rechts' 
        array('ˆ','&circ;','&#710;'), # Zirkumflex' 
        array('˜','&tilde;','&#732;') # kleine Tilde' 
    ); 
    if($input === false) return $html_entities; 
    //---------- 
    $utf8 = array(); 
    $html = array(); 
    foreach($html_entities as $entities) { 
        $utf8_char = array_slice($entities, 0, 1); 
        $html_code = array_slice($entities, 1, 2); 
        array_push($utf8, $utf8_char[0]); 
        array_push($html, $html_code[0], $html_code[1]); 
    } 
    # utf8 -> html    
    if($mode == 0) { 
        $output = str_replace($utf8, $html[0], htmlentities(_convert($input), ENT_NOQUOTES, "UTF-8", $double_encode = false));
		$output = str_replace("&nbsp;",' ',$output);
        #$output = str_replace($utf8, $html[0], utf8_encode($input)); 
    # utf8 <- html    
    } else { 
        $output = str_replace($html, $utf8, _convert(html_entity_decode($input))); 
    } 
    return $output; 
} 
function remove_accent($str) {  
    $a = array('À', 'Á', 'Â', 'Ã', 'Ä', 'Å', 'Æ', 'Ç', 'È', 'É', 'Ê', 'Ë', 'Ì', 'Í', 'Î', 'Ï', 'Ð', 'Ñ', 'Ò', 'Ó', 'Ô', 'Õ', 'Ö', 'Ø', 'Ù', 'Ú', 'Û', 'Ü', 'Ý', 'ß', 'à', 'á', 'â', 'ã', 'ä', 'å', 'æ', 'ç', 'è', 'é', 'ê', 'ë', 'ì', 'í', 'î', 'ï', 'ñ', 'ò', 'ó', 'ô', 'õ', 'ö', 'ø', 'ù', 'ú', 'û', 'ü', 'ý', 'ÿ', 'Ā', 'ā', 'Ă', 'ă', 'Ą', 'ą', 'Ć', 'ć', 'Ĉ', 'ĉ', 'Ċ', 'ċ', 'Č', 'č', 'Ď', 'ď', 'Đ', 'đ', 'Ē', 'ē', 'Ĕ', 'ĕ', 'Ė', 'ė', 'Ę', 'ę', 'Ě', 'ě', 'Ĝ', 'ĝ', 'Ğ', 'ğ', 'Ġ', 'ġ', 'Ģ', 'ģ', 'Ĥ', 'ĥ', 'Ħ', 'ħ', 'Ĩ', 'ĩ', 'Ī', 'ī', 'Ĭ', 'ĭ', 'Į', 'į', 'İ', 'ı', 'Ĳ', 'ĳ', 'Ĵ', 'ĵ', 'Ķ', 'ķ', 'Ĺ', 'ĺ', 'Ļ', 'ļ', 'Ľ', 'ľ', 'Ŀ', 'ŀ', 'Ł', 'ł', 'Ń', 'ń', 'Ņ', 'ņ', 'Ň', 'ň', 'ŉ', 'Ō', 'ō', 'Ŏ', 'ŏ', 'Ő', 'ő', 'Œ', 'œ', 'Ŕ', 'ŕ', 'Ŗ', 'ŗ', 'Ř', 'ř', 'Ś', 'ś', 'Ŝ', 'ŝ', 'Ş', 'ş', 'Š', 'š', 'Ţ', 'ţ', 'Ť', 'ť', 'Ŧ', 'ŧ', 'Ũ', 'ũ', 'Ū', 'ū', 'Ŭ', 'ŭ', 'Ů', 'ů', 'Ű', 'ű', 'Ų', 'ų', 'Ŵ', 'ŵ', 'Ŷ', 'ŷ', 'Ÿ', 'Ź', 'ź', 'Ż', 'ż', 'Ž', 'ž', 'ſ', 'ƒ', 'Ơ', 'ơ', 'Ư', 'ư', 'Ǎ', 'ǎ', 'Ǐ', 'ǐ', 'Ǒ', 'ǒ', 'Ǔ', 'ǔ', 'Ǖ', 'ǖ', 'Ǘ', 'ǘ', 'Ǚ', 'ǚ', 'Ǜ', 'ǜ', 'Ǻ', 'ǻ', 'Ǽ', 'ǽ', 'Ǿ', 'ǿ');  
    $b = array('A', 'A', 'A', 'A', 'A', 'A', 'AE', 'C', 'E', 'E', 'E', 'E', 'I', 'I', 'I', 'I', 'D', 'N', 'O', 'O', 'O', 'O', 'O', 'O', 'U', 'U', 'U', 'U', 'Y', 's', 'a', 'a', 'a', 'a', 'a', 'a', 'ae', 'c', 'e', 'e', 'e', 'e', 'i', 'i', 'i', 'i', 'n', 'o', 'o', 'o', 'o', 'o', 'o', 'u', 'u', 'u', 'u', 'y', 'y', 'A', 'a', 'A', 'a', 'A', 'a', 'C', 'c', 'C', 'c', 'C', 'c', 'C', 'c', 'D', 'd', 'D', 'd', 'E', 'e', 'E', 'e', 'E', 'e', 'E', 'e', 'E', 'e', 'G', 'g', 'G', 'g', 'G', 'g', 'G', 'g', 'H', 'h', 'H', 'h', 'I', 'i', 'I', 'i', 'I', 'i', 'I', 'i', 'I', 'i', 'IJ', 'ij', 'J', 'j', 'K', 'k', 'L', 'l', 'L', 'l', 'L', 'l', 'L', 'l', 'l', 'l', 'N', 'n', 'N', 'n', 'N', 'n', 'n', 'O', 'o', 'O', 'o', 'O', 'o', 'OE', 'oe', 'R', 'r', 'R', 'r', 'R', 'r', 'S', 's', 'S', 's', 'S', 's', 'S', 's', 'T', 't', 'T', 't', 'T', 't', 'U', 'u', 'U', 'u', 'U', 'u', 'U', 'u', 'U', 'u', 'U', 'u', 'W', 'w', 'Y', 'y', 'Y', 'Z', 'z', 'Z', 'z', 'Z', 'z', 's', 'f', 'O', 'o', 'U', 'u', 'A', 'a', 'I', 'i', 'O', 'o', 'U', 'u', 'U', 'u', 'U', 'u', 'U', 'u', 'U', 'u', 'A', 'a', 'AE', 'ae', 'O', 'o');  
    return str_replace($a, $b, $str);  
}  
?>